//
// Address.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Address represents an IPv4 or IPv6 IP address. */
public class Address: JSONEncodable {
    /** IP address. */
    public var addr: String?
    /** Mask length of the IP address. */
    public var prefixLen: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Addr"] = self.addr
        nillableDictionary["PrefixLen"] = self.prefixLen?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
