//
// AuthConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AuthConfig: JSONEncodable {
    public var username: String?
    public var password: String?
    public var email: String?
    public var serveraddress: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["username"] = self.username
        nillableDictionary["password"] = self.password
        nillableDictionary["email"] = self.email
        nillableDictionary["serveraddress"] = self.serveraddress
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
