//
// Container.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Container: JSONEncodable {
    /** The ID or name of the container to connect to the network. */
    public var container: String?
    public var endpointConfig: EndpointSettings?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Container"] = self.container
        nillableDictionary["EndpointConfig"] = self.endpointConfig?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
