//
// ContainerCreateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** OK response to ContainerCreate operation */
public class ContainerCreateResponse: JSONEncodable {
    /** The ID of the created container */
    public var id: String?
    /** Warnings encountered when creating the container */
    public var warnings: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Id"] = self.id
        nillableDictionary["Warnings"] = self.warnings?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
