//
// Container1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Container1: JSONEncodable {
    /** The ID or name of the container to disconnect from the network. */
    public var container: String?
    /** Force the container to disconnect from the network. */
    public var force: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Container"] = self.container
        nillableDictionary["Force"] = self.force
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
