//
// ContainerChangeResponseItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** change item in response to ContainerChanges operation */
public class ContainerChangeResponseItem: JSONEncodable {
    /** Path to file that has changed */
    public var path: String?
    /** Kind of change */
    public var kind: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Path"] = self.path
        nillableDictionary["Kind"] = self.kind?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
