//
// ContainerPruneResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ContainerPruneResponse: JSONEncodable {
    /** Container IDs that were deleted */
    public var containersDeleted: [String]?
    /** Disk space reclaimed in bytes */
    public var spaceReclaimed: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ContainersDeleted"] = self.containersDeleted?.encodeToJSON()
        nillableDictionary["SpaceReclaimed"] = self.spaceReclaimed?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
