//
// CreateImageInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CreateImageInfo: JSONEncodable {
    public var id: String?
    public var error: String?
    public var status: String?
    public var progress: String?
    public var progressDetail: ProgressDetail?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["error"] = self.error
        nillableDictionary["status"] = self.status
        nillableDictionary["progress"] = self.progress
        nillableDictionary["progressDetail"] = self.progressDetail?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
