//
// DeviceMapping.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A device mapping between the host and container */
public class DeviceMapping: JSONEncodable {
    public var pathOnHost: String?
    public var pathInContainer: String?
    public var cgroupPermissions: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["PathOnHost"] = self.pathOnHost
        nillableDictionary["PathInContainer"] = self.pathInContainer
        nillableDictionary["CgroupPermissions"] = self.cgroupPermissions
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
