//
// DistributionInspectResponsePlatforms.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class DistributionInspectResponsePlatforms: JSONEncodable {
    public var architecture: String?
    public var OS: String?
    public var oSVersion: String?
    public var oSFeatures: [String]?
    public var variant: String?
    public var features: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Architecture"] = self.architecture
        nillableDictionary["OS"] = self.OS
        nillableDictionary["OSVersion"] = self.oSVersion
        nillableDictionary["OSFeatures"] = self.oSFeatures?.encodeToJSON()
        nillableDictionary["Variant"] = self.variant
        nillableDictionary["Features"] = self.features?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
