//
// DistributionInspectResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class DistributionInspectResponse: JSONEncodable {
    public var descriptor: DistributionInspectResponseDescriptor?
    /** An array containing all platforms supported by the image */
    public var platforms: [DistributionInspectResponsePlatforms]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Descriptor"] = self.descriptor?.encodeToJSON()
        nillableDictionary["Platforms"] = self.platforms?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
