//
// EngineDescription.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** EngineDescription provides information about an engine. */
public class EngineDescription: JSONEncodable {
    public var engineVersion: String?
    public var labels: [String:String]?
    public var plugins: [EngineDescriptionPlugins]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["EngineVersion"] = self.engineVersion
        nillableDictionary["Labels"] = self.labels?.encodeToJSON()
        nillableDictionary["Plugins"] = self.plugins?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
