//
// ExecInspectResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ExecInspectResponse: JSONEncodable {
    public var canRemove: Bool?
    public var detachKeys: String?
    public var ID: String?
    public var running: Bool?
    public var exitCode: Int32?
    public var processConfig: ProcessConfig?
    public var openStdin: Bool?
    public var openStderr: Bool?
    public var openStdout: Bool?
    public var containerID: String?
    /** The system process ID for the exec process. */
    public var pid: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["CanRemove"] = self.canRemove
        nillableDictionary["DetachKeys"] = self.detachKeys
        nillableDictionary["ID"] = self.ID
        nillableDictionary["Running"] = self.running
        nillableDictionary["ExitCode"] = self.exitCode?.encodeToJSON()
        nillableDictionary["ProcessConfig"] = self.processConfig?.encodeToJSON()
        nillableDictionary["OpenStdin"] = self.openStdin
        nillableDictionary["OpenStderr"] = self.openStderr
        nillableDictionary["OpenStdout"] = self.openStdout
        nillableDictionary["ContainerID"] = self.containerID
        nillableDictionary["Pid"] = self.pid?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
