//
// GenericResourcesInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class GenericResourcesInner: JSONEncodable {
    public var namedResourceSpec: GenericResourcesInnerNamedResourceSpec?
    public var discreteResourceSpec: GenericResourcesInnerDiscreteResourceSpec?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["NamedResourceSpec"] = self.namedResourceSpec?.encodeToJSON()
        nillableDictionary["DiscreteResourceSpec"] = self.discreteResourceSpec?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
