//
// GenericResourcesInnerDiscreteResourceSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class GenericResourcesInnerDiscreteResourceSpec: JSONEncodable {
    public var kind: String?
    public var value: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Kind"] = self.kind
        nillableDictionary["Value"] = self.value?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
