//
// HostConfigLogConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The logging configuration for this container */
public class HostConfigLogConfig: JSONEncodable {
    public enum ModelType: String { 
        case JsonFile = "json-file"
        case Syslog = "syslog"
        case Journald = "journald"
        case Gelf = "gelf"
        case Fluentd = "fluentd"
        case Awslogs = "awslogs"
        case Splunk = "splunk"
        case Etwlogs = "etwlogs"
        case None = "none"
    }
    public var type: ModelType?
    public var config: [String:String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Type"] = self.type?.rawValue
        nillableDictionary["Config"] = self.config?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
