//
// ImageSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ImageSummary: JSONEncodable {
    public var id: String?
    public var parentId: String?
    public var repoTags: [String]?
    public var repoDigests: [String]?
    public var created: Int32?
    public var size: Int32?
    public var sharedSize: Int32?
    public var virtualSize: Int32?
    public var labels: [String:String]?
    public var containers: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Id"] = self.id
        nillableDictionary["ParentId"] = self.parentId
        nillableDictionary["RepoTags"] = self.repoTags?.encodeToJSON()
        nillableDictionary["RepoDigests"] = self.repoDigests?.encodeToJSON()
        nillableDictionary["Created"] = self.created?.encodeToJSON()
        nillableDictionary["Size"] = self.size?.encodeToJSON()
        nillableDictionary["SharedSize"] = self.sharedSize?.encodeToJSON()
        nillableDictionary["VirtualSize"] = self.virtualSize?.encodeToJSON()
        nillableDictionary["Labels"] = self.labels?.encodeToJSON()
        nillableDictionary["Containers"] = self.containers?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
