//
// ImageSearchResponseItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ImageSearchResponseItem: JSONEncodable {
    public var description: String?
    public var isOfficial: Bool?
    public var isAutomated: Bool?
    public var name: String?
    public var starCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["description"] = self.description
        nillableDictionary["is_official"] = self.isOfficial
        nillableDictionary["is_automated"] = self.isAutomated
        nillableDictionary["name"] = self.name
        nillableDictionary["star_count"] = self.starCount?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
