//
// ImageDeleteResponseItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ImageDeleteResponseItem: JSONEncodable {
    /** The image ID of an image that was untagged */
    public var untagged: String?
    /** The image ID of an image that was deleted */
    public var deleted: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Untagged"] = self.untagged
        nillableDictionary["Deleted"] = self.deleted
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
