//
// ImagePruneResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ImagePruneResponse: JSONEncodable {
    /** Images that were deleted */
    public var imagesDeleted: [ImageDeleteResponseItem]?
    /** Disk space reclaimed in bytes */
    public var spaceReclaimed: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ImagesDeleted"] = self.imagesDeleted?.encodeToJSON()
        nillableDictionary["SpaceReclaimed"] = self.spaceReclaimed?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
