//
// JoinTokens.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** JoinTokens contains the tokens workers and managers need to join the swarm.  */
public class JoinTokens: JSONEncodable {
    /** The token workers can use to join the swarm.  */
    public var worker: String?
    /** The token managers can use to join the swarm.  */
    public var manager: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Worker"] = self.worker
        nillableDictionary["Manager"] = self.manager
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
