//
// MountTmpfsOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Optional configuration for the &#x60;tmpfs&#x60; type. */
public class MountTmpfsOptions: JSONEncodable {
    /** The size for the tmpfs mount in bytes. */
    public var sizeBytes: Int64?
    /** The permission mode for the tmpfs mount in an integer. */
    public var mode: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["SizeBytes"] = self.sizeBytes?.encodeToJSON()
        nillableDictionary["Mode"] = self.mode?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
