//
// MountPoint.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A mount point inside a container */
public class MountPoint: JSONEncodable {
    public var type: String?
    public var name: String?
    public var source: String?
    public var destination: String?
    public var driver: String?
    public var mode: String?
    public var RW: Bool?
    public var propagation: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Type"] = self.type
        nillableDictionary["Name"] = self.name
        nillableDictionary["Source"] = self.source
        nillableDictionary["Destination"] = self.destination
        nillableDictionary["Driver"] = self.driver
        nillableDictionary["Mode"] = self.mode
        nillableDictionary["RW"] = self.RW
        nillableDictionary["Propagation"] = self.propagation
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
