//
// MountVolumeOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Optional configuration for the &#x60;volume&#x60; type. */
public class MountVolumeOptions: JSONEncodable {
    /** Populate volume with data from the target. */
    public var noCopy: Bool?
    /** User-defined key/value metadata. */
    public var labels: [String:String]?
    public var driverConfig: MountVolumeOptionsDriverConfig?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["NoCopy"] = self.noCopy
        nillableDictionary["Labels"] = self.labels?.encodeToJSON()
        nillableDictionary["DriverConfig"] = self.driverConfig?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
