//
// Network.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Network: JSONEncodable {
    public var name: String?
    public var id: String?
    public var created: String?
    public var scope: String?
    public var driver: String?
    public var enableIPv6: Bool?
    public var IPAM: IPAM?
    public var _internal: Bool?
    public var attachable: Bool?
    public var ingress: Bool?
    public var containers: [String:NetworkContainer]?
    public var options: [String:String]?
    public var labels: [String:String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Id"] = self.id
        nillableDictionary["Created"] = self.created
        nillableDictionary["Scope"] = self.scope
        nillableDictionary["Driver"] = self.driver
        nillableDictionary["EnableIPv6"] = self.enableIPv6
        nillableDictionary["IPAM"] = self.IPAM?.encodeToJSON()
        nillableDictionary["Internal"] = self._internal
        nillableDictionary["Attachable"] = self.attachable
        nillableDictionary["Ingress"] = self.ingress
        nillableDictionary["Containers"] = self.containers?.encodeToJSON()
        nillableDictionary["Options"] = self.options?.encodeToJSON()
        nillableDictionary["Labels"] = self.labels?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
