//
// NetworkContainer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class NetworkContainer: JSONEncodable {
    public var name: String?
    public var endpointID: String?
    public var macAddress: String?
    public var iPv4Address: String?
    public var iPv6Address: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["EndpointID"] = self.endpointID
        nillableDictionary["MacAddress"] = self.macAddress
        nillableDictionary["IPv4Address"] = self.iPv4Address
        nillableDictionary["IPv6Address"] = self.iPv6Address
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
