//
// NodeStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** NodeStatus represents the status of a node.  It provides the current status of the node, as seen by the manager.  */
public class NodeStatus: JSONEncodable {
    public var state: NodeState?
    public var message: String?
    /** IP address of the node. */
    public var addr: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["State"] = self.state?.encodeToJSON()
        nillableDictionary["Message"] = self.message
        nillableDictionary["Addr"] = self.addr
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
