//
// NodeSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class NodeSpec: JSONEncodable {
    public enum Role: String { 
        case Worker = "worker"
        case Manager = "manager"
    }
    public enum Availability: String { 
        case Active = "active"
        case Pause = "pause"
        case Drain = "drain"
    }
    /** Name for the node. */
    public var name: String?
    /** User-defined key/value metadata. */
    public var labels: [String:String]?
    /** Role of the node. */
    public var role: Role?
    /** Availability of the node. */
    public var availability: Availability?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Labels"] = self.labels?.encodeToJSON()
        nillableDictionary["Role"] = self.role?.rawValue
        nillableDictionary["Availability"] = self.availability?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
