//
// NodeDescription.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** NodeDescription encapsulates the properties of the Node as reported by the agent.  */
public class NodeDescription: JSONEncodable {
    public var hostname: String?
    public var platform: Platform?
    public var resources: ResourceObject?
    public var engine: EngineDescription?
    public var tLSInfo: TLSInfo?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Hostname"] = self.hostname
        nillableDictionary["Platform"] = self.platform?.encodeToJSON()
        nillableDictionary["Resources"] = self.resources?.encodeToJSON()
        nillableDictionary["Engine"] = self.engine?.encodeToJSON()
        nillableDictionary["TLSInfo"] = self.tLSInfo?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
