//
// PeerNode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents a peer-node in the swarm */
public class PeerNode: JSONEncodable {
    /** Unique identifier of for this node in the swarm. */
    public var nodeID: String?
    /** IP address and ports at which this node can be reached.  */
    public var addr: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["NodeID"] = self.nodeID
        nillableDictionary["Addr"] = self.addr
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
