//
// Plugin.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A plugin for the Engine API */
public class Plugin: JSONEncodable {
    public var id: String?
    public var name: String?
    /** True if the plugin is running. False if the plugin is not running, only installed. */
    public var enabled: Bool?
    public var settings: PluginSettings?
    /** plugin remote reference used to push/pull the plugin */
    public var pluginReference: String?
    public var config: PluginConfig?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Id"] = self.id
        nillableDictionary["Name"] = self.name
        nillableDictionary["Enabled"] = self.enabled
        nillableDictionary["Settings"] = self.settings?.encodeToJSON()
        nillableDictionary["PluginReference"] = self.pluginReference
        nillableDictionary["Config"] = self.config?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
