//
// PluginConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The config of a plugin. */
public class PluginConfig: JSONEncodable {
    /** Docker Version used to create the plugin */
    public var dockerVersion: String?
    public var description: String?
    public var documentation: String?
    public var interface: PluginConfigInterface?
    public var entrypoint: [String]?
    public var workDir: String?
    public var user: PluginConfigUser?
    public var network: PluginConfigNetwork?
    public var linux: PluginConfigLinux?
    public var propagatedMount: String?
    public var ipcHost: Bool?
    public var pidHost: Bool?
    public var mounts: [PluginMount]?
    public var env: [PluginEnv]?
    public var args: PluginConfigArgs?
    public var rootfs: PluginConfigRootfs?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["DockerVersion"] = self.dockerVersion
        nillableDictionary["Description"] = self.description
        nillableDictionary["Documentation"] = self.documentation
        nillableDictionary["Interface"] = self.interface?.encodeToJSON()
        nillableDictionary["Entrypoint"] = self.entrypoint?.encodeToJSON()
        nillableDictionary["WorkDir"] = self.workDir
        nillableDictionary["User"] = self.user?.encodeToJSON()
        nillableDictionary["Network"] = self.network?.encodeToJSON()
        nillableDictionary["Linux"] = self.linux?.encodeToJSON()
        nillableDictionary["PropagatedMount"] = self.propagatedMount
        nillableDictionary["IpcHost"] = self.ipcHost
        nillableDictionary["PidHost"] = self.pidHost
        nillableDictionary["Mounts"] = self.mounts?.encodeToJSON()
        nillableDictionary["Env"] = self.env?.encodeToJSON()
        nillableDictionary["Args"] = self.args?.encodeToJSON()
        nillableDictionary["rootfs"] = self.rootfs?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
