//
// PluginSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Settings that can be modified by users. */
public class PluginSettings: JSONEncodable {
    public var mounts: [PluginMount]?
    public var env: [String]?
    public var args: [String]?
    public var devices: [PluginDevice]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Mounts"] = self.mounts?.encodeToJSON()
        nillableDictionary["Env"] = self.env?.encodeToJSON()
        nillableDictionary["Args"] = self.args?.encodeToJSON()
        nillableDictionary["Devices"] = self.devices?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
