//
// PluginConfigInterface.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The interface between Docker and the plugin */
public class PluginConfigInterface: JSONEncodable {
    public var types: [PluginInterfaceType]?
    public var socket: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Types"] = self.types?.encodeToJSON()
        nillableDictionary["Socket"] = self.socket
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
