//
// PluginMount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PluginMount: JSONEncodable {
    public var name: String?
    public var description: String?
    public var settable: [String]?
    public var source: String?
    public var destination: String?
    public var type: String?
    public var options: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Description"] = self.description
        nillableDictionary["Settable"] = self.settable?.encodeToJSON()
        nillableDictionary["Source"] = self.source
        nillableDictionary["Destination"] = self.destination
        nillableDictionary["Type"] = self.type
        nillableDictionary["Options"] = self.options?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
