//
// PluginInterfaceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PluginInterfaceType: JSONEncodable {
    public var _prefix: String?
    public var capability: String?
    public var version: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Prefix"] = self._prefix
        nillableDictionary["Capability"] = self.capability
        nillableDictionary["Version"] = self.version
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
