//
// Port.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An open port on a container */
public class Port: JSONEncodable {
    public enum ModelType: String { 
        case Tcp = "tcp"
        case Udp = "udp"
    }
    public var IP: String?
    /** Port on the container */
    public var privatePort: Int32?
    /** Port exposed on the host */
    public var publicPort: Int32?
    public var type: ModelType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["IP"] = self.IP
        nillableDictionary["PrivatePort"] = self.privatePort?.encodeToJSON()
        nillableDictionary["PublicPort"] = self.publicPort?.encodeToJSON()
        nillableDictionary["Type"] = self.type?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
