//
// PortBinding.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** PortBinding represents a binding between a host IP address and a host port.  */
public class PortBinding: JSONEncodable {
    /** Host IP address that the container&#39;s port is mapped to. */
    public var hostIp: String?
    /** Host port number that the container&#39;s port is mapped to. */
    public var hostPort: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["HostIp"] = self.hostIp
        nillableDictionary["HostPort"] = self.hostPort
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
