//
// ServiceUpdateStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The status of a service update. */
public class ServiceUpdateStatus: JSONEncodable {
    public enum State: String { 
        case Updating = "updating"
        case Paused = "paused"
        case Completed = "completed"
    }
    public var state: State?
    public var startedAt: String?
    public var completedAt: String?
    public var message: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["State"] = self.state?.rawValue
        nillableDictionary["StartedAt"] = self.startedAt
        nillableDictionary["CompletedAt"] = self.completedAt
        nillableDictionary["Message"] = self.message
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
