//
// Service.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Service: JSONEncodable {
    public var ID: String?
    public var version: ObjectVersion?
    public var createdAt: String?
    public var updatedAt: String?
    public var spec: ServiceSpec?
    public var endpoint: ServiceEndpoint?
    public var updateStatus: ServiceUpdateStatus?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ID"] = self.ID
        nillableDictionary["Version"] = self.version?.encodeToJSON()
        nillableDictionary["CreatedAt"] = self.createdAt
        nillableDictionary["UpdatedAt"] = self.updatedAt
        nillableDictionary["Spec"] = self.spec?.encodeToJSON()
        nillableDictionary["Endpoint"] = self.endpoint?.encodeToJSON()
        nillableDictionary["UpdateStatus"] = self.updateStatus?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
