//
// ServiceSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** User modifiable configuration for a service. */
public class ServiceSpec: JSONEncodable {
    /** Name of the service. */
    public var name: String?
    /** User-defined key/value metadata. */
    public var labels: [String:String]?
    public var taskTemplate: TaskSpec?
    public var mode: ServiceSpecMode?
    public var updateConfig: ServiceSpecUpdateConfig?
    public var rollbackConfig: ServiceSpecRollbackConfig?
    /** Array of network names or IDs to attach the service to. */
    public var networks: [TaskSpecNetworks]?
    public var endpointSpec: EndpointSpec?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Labels"] = self.labels?.encodeToJSON()
        nillableDictionary["TaskTemplate"] = self.taskTemplate?.encodeToJSON()
        nillableDictionary["Mode"] = self.mode?.encodeToJSON()
        nillableDictionary["UpdateConfig"] = self.updateConfig?.encodeToJSON()
        nillableDictionary["RollbackConfig"] = self.rollbackConfig?.encodeToJSON()
        nillableDictionary["Networks"] = self.networks?.encodeToJSON()
        nillableDictionary["EndpointSpec"] = self.endpointSpec?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
