//
// ServiceEndpointVirtualIPs.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ServiceEndpointVirtualIPs: JSONEncodable {
    public var networkID: String?
    public var addr: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["NetworkID"] = self.networkID
        nillableDictionary["Addr"] = self.addr
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
