//
// SwarmSpecOrchestration.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Orchestration configuration. */
public class SwarmSpecOrchestration: JSONEncodable {
    /** The number of historic tasks to keep per instance or node. If negative, never remove completed or failed tasks. */
    public var taskHistoryRetentionLimit: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["TaskHistoryRetentionLimit"] = self.taskHistoryRetentionLimit?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
