//
// SwarmSpecTaskDefaultsLogDriver.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The log driver to use for tasks created in the orchestrator if unspecified by a service.  Updating this value only affects new tasks. Existing tasks continue to use their previously configured log driver until recreated.  */
public class SwarmSpecTaskDefaultsLogDriver: JSONEncodable {
    /** The log driver to use as a default for new tasks.  */
    public var name: String?
    /** Driver-specific options for the selectd log driver, specified as key/value pairs.  */
    public var options: [String:String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Options"] = self.options?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
