//
// SwarmSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** User modifiable swarm configuration. */
public class SwarmSpec: JSONEncodable {
    /** Name of the swarm. */
    public var name: String?
    /** User-defined key/value metadata. */
    public var labels: [String:String]?
    public var orchestration: SwarmSpecOrchestration?
    public var raft: SwarmSpecRaft?
    public var dispatcher: SwarmSpecDispatcher?
    public var cAConfig: SwarmSpecCAConfig?
    public var encryptionConfig: SwarmSpecEncryptionConfig?
    public var taskDefaults: SwarmSpecTaskDefaults?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Labels"] = self.labels?.encodeToJSON()
        nillableDictionary["Orchestration"] = self.orchestration?.encodeToJSON()
        nillableDictionary["Raft"] = self.raft?.encodeToJSON()
        nillableDictionary["Dispatcher"] = self.dispatcher?.encodeToJSON()
        nillableDictionary["CAConfig"] = self.cAConfig?.encodeToJSON()
        nillableDictionary["EncryptionConfig"] = self.encryptionConfig?.encodeToJSON()
        nillableDictionary["TaskDefaults"] = self.taskDefaults?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
