//
// SystemDataUsageResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SystemDataUsageResponse: JSONEncodable {
    public var layersSize: Int64?
    public var images: [ImageSummary]?
    public var containers: [ContainerSummary]?
    public var volumes: [Volume]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["LayersSize"] = self.layersSize?.encodeToJSON()
        nillableDictionary["Images"] = self.images?.encodeToJSON()
        nillableDictionary["Containers"] = self.containers?.encodeToJSON()
        nillableDictionary["Volumes"] = self.volumes?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
