//
// SystemEventsResponseActor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SystemEventsResponseActor: JSONEncodable {
    /** The ID of the object emitting the event */
    public var ID: String?
    /** Various key/value attributes of the object, depending on its type */
    public var attributes: [String:String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ID"] = self.ID
        nillableDictionary["Attributes"] = self.attributes?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
