//
// TaskSpecContainerSpecPrivileges.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Security options for the container */
public class TaskSpecContainerSpecPrivileges: JSONEncodable {
    public var credentialSpec: TaskSpecContainerSpecPrivilegesCredentialSpec?
    public var sELinuxContext: TaskSpecContainerSpecPrivilegesSELinuxContext?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["CredentialSpec"] = self.credentialSpec?.encodeToJSON()
        nillableDictionary["SELinuxContext"] = self.sELinuxContext?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
