//
// TaskSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** User modifiable task configuration. */
public class TaskSpec: JSONEncodable {
    public var pluginSpec: TaskSpecPluginSpec?
    public var containerSpec: TaskSpecContainerSpec?
    public var resources: TaskSpecResources?
    public var restartPolicy: TaskSpecRestartPolicy?
    public var placement: TaskSpecPlacement?
    /** A counter that triggers an update even if no relevant parameters have been changed. */
    public var forceUpdate: Int32?
    /** Runtime is the type of runtime specified for the task executor. */
    public var runtime: String?
    public var networks: [TaskSpecNetworks]?
    public var logDriver: TaskSpecLogDriver?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["PluginSpec"] = self.pluginSpec?.encodeToJSON()
        nillableDictionary["ContainerSpec"] = self.containerSpec?.encodeToJSON()
        nillableDictionary["Resources"] = self.resources?.encodeToJSON()
        nillableDictionary["RestartPolicy"] = self.restartPolicy?.encodeToJSON()
        nillableDictionary["Placement"] = self.placement?.encodeToJSON()
        nillableDictionary["ForceUpdate"] = self.forceUpdate?.encodeToJSON()
        nillableDictionary["Runtime"] = self.runtime
        nillableDictionary["Networks"] = self.networks?.encodeToJSON()
        nillableDictionary["LogDriver"] = self.logDriver?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
