//
// TaskSpecContainerSpecFile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** File represents a specific target that is backed by a file. */
public class TaskSpecContainerSpecFile: JSONEncodable {
    /** Name represents the final filename in the filesystem. */
    public var name: String?
    /** UID represents the file UID. */
    public var UID: String?
    /** GID represents the file GID. */
    public var GID: String?
    /** Mode represents the FileMode of the file. */
    public var mode: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["UID"] = self.UID
        nillableDictionary["GID"] = self.GID
        nillableDictionary["Mode"] = self.mode?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
