//
// TaskSpecPlacementSpread.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class TaskSpecPlacementSpread: JSONEncodable {
    /** label descriptor, such as engine.labels.az */
    public var spreadDescriptor: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["SpreadDescriptor"] = self.spreadDescriptor
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
