//
// TaskSpecRestartPolicy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specification for the restart policy which applies to containers created as part of this service. */
public class TaskSpecRestartPolicy: JSONEncodable {
    public enum Condition: String { 
        case None = "none"
        case OnFailure = "on-failure"
        case Any = "any"
    }
    /** Condition for restart. */
    public var condition: Condition?
    /** Delay between restart attempts. */
    public var delay: Int64?
    /** Maximum attempts to restart a given container before giving up (default value is 0, which is ignored). */
    public var maxAttempts: Int64?
    /** Windows is the time window used to evaluate the restart policy (default value is 0, which is unbounded). */
    public var window: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Condition"] = self.condition?.rawValue
        nillableDictionary["Delay"] = self.delay?.encodeToJSON()
        nillableDictionary["MaxAttempts"] = self.maxAttempts?.encodeToJSON()
        nillableDictionary["Window"] = self.window?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
