//
// TaskSpecPluginSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Invalid when specified with &#x60;ContainerSpec&#x60;. *(Experimental release only.)* */
public class TaskSpecPluginSpec: JSONEncodable {
    /** The name or &#39;alias&#39; to use for the plugin. */
    public var name: String?
    /** The plugin image reference to use. */
    public var remote: String?
    /** Disable the plugin once scheduled. */
    public var disabled: Bool?
    public var pluginPrivilege: [Body]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Remote"] = self.remote
        nillableDictionary["Disabled"] = self.disabled
        nillableDictionary["PluginPrivilege"] = self.pluginPrivilege?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
