//
// Task.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Task: JSONEncodable {
    /** The ID of the task. */
    public var ID: String?
    public var version: ObjectVersion?
    public var createdAt: String?
    public var updatedAt: String?
    /** Name of the task. */
    public var name: String?
    /** User-defined key/value metadata. */
    public var labels: [String:String]?
    public var spec: TaskSpec?
    /** The ID of the service this task is part of. */
    public var serviceID: String?
    public var slot: Int32?
    /** The ID of the node that this task is on. */
    public var nodeID: String?
    public var assignedGenericResources: GenericResources?
    public var status: TaskStatus?
    public var desiredState: TaskState?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ID"] = self.ID
        nillableDictionary["Version"] = self.version?.encodeToJSON()
        nillableDictionary["CreatedAt"] = self.createdAt
        nillableDictionary["UpdatedAt"] = self.updatedAt
        nillableDictionary["Name"] = self.name
        nillableDictionary["Labels"] = self.labels?.encodeToJSON()
        nillableDictionary["Spec"] = self.spec?.encodeToJSON()
        nillableDictionary["ServiceID"] = self.serviceID
        nillableDictionary["Slot"] = self.slot?.encodeToJSON()
        nillableDictionary["NodeID"] = self.nodeID
        nillableDictionary["AssignedGenericResources"] = self.assignedGenericResources?.encodeToJSON()
        nillableDictionary["Status"] = self.status?.encodeToJSON()
        nillableDictionary["DesiredState"] = self.desiredState?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
