//
// TaskSpecResources.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Resource requirements which apply to each individual container created as part of the service. */
public class TaskSpecResources: JSONEncodable {
    /** Define resources limits. */
    public var limits: ResourceObject?
    /** Define resources reservation. */
    public var reservation: ResourceObject?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Limits"] = self.limits?.encodeToJSON()
        nillableDictionary["Reservation"] = self.reservation?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
