//
// TaskStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class TaskStatus: JSONEncodable {
    public var timestamp: String?
    public var state: TaskState?
    public var message: String?
    public var err: String?
    public var containerStatus: TaskStatusContainerStatus?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Timestamp"] = self.timestamp
        nillableDictionary["State"] = self.state?.encodeToJSON()
        nillableDictionary["Message"] = self.message
        nillableDictionary["Err"] = self.err
        nillableDictionary["ContainerStatus"] = self.containerStatus?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
