//
// TLSInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Information about the issuer of leaf TLS certificates and the trusted root CA certificate */
public class TLSInfo: JSONEncodable {
    /** The root CA certificate(s) that are used to validate leaf TLS certificates */
    public var trustRoot: String?
    /** The base64-url-safe-encoded raw subject bytes of the issuer */
    public var certIssuerSubject: String?
    /** The base64-url-safe-encoded raw public key bytes of the issuer */
    public var certIssuerPublicKey: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["TrustRoot"] = self.trustRoot
        nillableDictionary["CertIssuerSubject"] = self.certIssuerSubject
        nillableDictionary["CertIssuerPublicKey"] = self.certIssuerPublicKey
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
