//
// ExecAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class ExecAPI: APIBase {
    /**
     Create an exec instance
     
     - parameter execConfig: (body) Exec configuration 
     - parameter id: (path) ID or name of container 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func containerExec(execConfig execConfig: ExecConfig, id: String, completion: ((data: IdResponse?, error: ErrorType?) -> Void)) {
        containerExecWithRequestBuilder(execConfig: execConfig, id: id).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Create an exec instance
     - POST /containers/{id}/exec
     - Run a command inside a running container.
     - examples: [{example={
  "Id" : "Id"
}, contentType=application/json}]
     
     - parameter execConfig: (body) Exec configuration 
     - parameter id: (path) ID or name of container 

     - returns: RequestBuilder<IdResponse> 
     */
    public class func containerExecWithRequestBuilder(execConfig execConfig: ExecConfig, id: String) -> RequestBuilder<IdResponse> {
        var path = "/containers/{id}/exec"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = execConfig.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<IdResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Inspect an exec instance
     
     - parameter id: (path) Exec instance ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func execInspect(id id: String, completion: ((data: ExecInspectResponse?, error: ErrorType?) -> Void)) {
        execInspectWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Inspect an exec instance
     - GET /exec/{id}/json
     - Return low-level information about an exec instance.
     - examples: [{example={
  "CanRemove" : false,
  "ContainerID" : "b53ee82b53a40c7dca428523e34f741f3abc51d9f297a14ff874bf761b995126",
  "DetachKeys" : "",
  "ExitCode" : 2,
  "ID" : "f33bbfb39f5b142420f4759b2348913bd4a8d1a6d7fd56499cb41a1bb91d7b3b",
  "OpenStderr" : true,
  "OpenStdin" : true,
  "OpenStdout" : true,
  "ProcessConfig" : {
    "arguments" : [ "-c", "exit 2" ],
    "entrypoint" : "sh",
    "privileged" : false,
    "tty" : true,
    "user" : "1000"
  },
  "Running" : false,
  "Pid" : 42000
}, contentType=application/json}]
     
     - parameter id: (path) Exec instance ID 

     - returns: RequestBuilder<ExecInspectResponse> 
     */
    public class func execInspectWithRequestBuilder(id id: String) -> RequestBuilder<ExecInspectResponse> {
        var path = "/exec/{id}/json"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ExecInspectResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Resize an exec instance
     
     - parameter id: (path) Exec instance ID 
     - parameter h: (query) Height of the TTY session in characters (optional)
     - parameter w: (query) Width of the TTY session in characters (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func execResize(id id: String, h: Int32? = nil, w: Int32? = nil, completion: ((error: ErrorType?) -> Void)) {
        execResizeWithRequestBuilder(id: id, h: h, w: w).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Resize an exec instance
     - POST /exec/{id}/resize
     - Resize the TTY session used by an exec instance. This endpoint only works if `tty` was specified as part of creating and starting the exec instance.
     
     - parameter id: (path) Exec instance ID 
     - parameter h: (query) Height of the TTY session in characters (optional)
     - parameter w: (query) Width of the TTY session in characters (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func execResizeWithRequestBuilder(id id: String, h: Int32? = nil, w: Int32? = nil) -> RequestBuilder<Void> {
        var path = "/exec/{id}/resize"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "h": h?.encodeToJSON(),
            "w": w?.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Start an exec instance
     
     - parameter id: (path) Exec instance ID 
     - parameter execStartConfig: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func execStart(id id: String, execStartConfig: ExecStartConfig? = nil, completion: ((error: ErrorType?) -> Void)) {
        execStartWithRequestBuilder(id: id, execStartConfig: execStartConfig).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Start an exec instance
     - POST /exec/{id}/start
     - Starts a previously set up exec instance. If detach is true, this endpoint returns immediately after starting the command. Otherwise, it sets up an interactive session with the command.
     
     - parameter id: (path) Exec instance ID 
     - parameter execStartConfig: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func execStartWithRequestBuilder(id id: String, execStartConfig: ExecStartConfig? = nil) -> RequestBuilder<Void> {
        var path = "/exec/{id}/start"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = execStartConfig?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
