//
// SecretAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class SecretAPI: APIBase {
    /**
     Create a secret
     
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func secretCreate(body body: ? = nil, completion: ((data: IdResponse?, error: ErrorType?) -> Void)) {
        secretCreateWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Create a secret
     - POST /secrets/create
     - examples: [{example={
  "Id" : "Id"
}, contentType=application/json}]
     
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<IdResponse> 
     */
    public class func secretCreateWithRequestBuilder(body body: ? = nil) -> RequestBuilder<IdResponse> {
        let path = "/secrets/create"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = body?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<IdResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Delete a secret
     
     - parameter id: (path) ID of the secret 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func secretDelete(id id: String, completion: ((error: ErrorType?) -> Void)) {
        secretDeleteWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Delete a secret
     - DELETE /secrets/{id}
     
     - parameter id: (path) ID of the secret 

     - returns: RequestBuilder<Void> 
     */
    public class func secretDeleteWithRequestBuilder(id id: String) -> RequestBuilder<Void> {
        var path = "/secrets/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Inspect a secret
     
     - parameter id: (path) ID of the secret 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func secretInspect(id id: String, completion: ((data: Secret?, error: ErrorType?) -> Void)) {
        secretInspectWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Inspect a secret
     - GET /secrets/{id}
     - examples: [{example={
  "ID" : "ktnbjxoalbkvbvedmg1urrz8h",
  "Version" : {
    "Index" : 11
  },
  "CreatedAt" : "2016-11-05T01:20:17.327670065Z",
  "UpdatedAt" : "2016-11-05T01:20:17.327670065Z",
  "Spec" : {
    "Name" : "app-dev.crt",
    "Labels" : {
      "foo" : "bar"
    },
    "Driver" : {
      "Name" : "secret-bucket",
      "Options" : {
        "OptionA" : "value for driver option A",
        "OptionB" : "value for driver option B"
      }
    }
  }
}, contentType=application/json}]
     
     - parameter id: (path) ID of the secret 

     - returns: RequestBuilder<Secret> 
     */
    public class func secretInspectWithRequestBuilder(id id: String) -> RequestBuilder<Secret> {
        var path = "/secrets/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Secret>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     List secrets
     
     - parameter filters: (query) A JSON encoded value of the filters (a &#x60;map[string][]string&#x60;) to process on the secrets list. Available filters:  - &#x60;id&#x3D;&lt;secret id&gt;&#x60; - &#x60;label&#x3D;&lt;key&gt; or label&#x3D;&lt;key&gt;&#x3D;value&#x60; - &#x60;name&#x3D;&lt;secret name&gt;&#x60; - &#x60;names&#x3D;&lt;secret name&gt;&#x60;  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func secretList(filters filters: String? = nil, completion: ((data: [Secret]?, error: ErrorType?) -> Void)) {
        secretListWithRequestBuilder(filters: filters).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List secrets
     - GET /secrets
     - examples: [{example=[ {
  "ID" : "blt1owaxmitz71s9v5zh81zun",
  "Version" : {
    "Index" : 85
  },
  "CreatedAt" : "2017-07-20T13:55:28.678958722Z",
  "UpdatedAt" : "2017-07-20T13:55:28.678958722Z",
  "Spec" : {
    "Name" : "mysql-passwd",
    "Labels" : {
      "some.label" : "some.value"
    },
    "Driver" : {
      "Name" : "secret-bucket",
      "Options" : {
        "OptionA" : "value for driver option A",
        "OptionB" : "value for driver option B"
      }
    }
  }
}, {
  "ID" : "ktnbjxoalbkvbvedmg1urrz8h",
  "Version" : {
    "Index" : 11
  },
  "CreatedAt" : "2016-11-05T01:20:17.327670065Z",
  "UpdatedAt" : "2016-11-05T01:20:17.327670065Z",
  "Spec" : {
    "Name" : "app-dev.crt",
    "Labels" : {
      "foo" : "bar"
    }
  }
} ], contentType=application/json}]
     
     - parameter filters: (query) A JSON encoded value of the filters (a &#x60;map[string][]string&#x60;) to process on the secrets list. Available filters:  - &#x60;id&#x3D;&lt;secret id&gt;&#x60; - &#x60;label&#x3D;&lt;key&gt; or label&#x3D;&lt;key&gt;&#x3D;value&#x60; - &#x60;name&#x3D;&lt;secret name&gt;&#x60; - &#x60;names&#x3D;&lt;secret name&gt;&#x60;  (optional)

     - returns: RequestBuilder<[Secret]> 
     */
    public class func secretListWithRequestBuilder(filters filters: String? = nil) -> RequestBuilder<[Secret]> {
        let path = "/secrets"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "filters": filters
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[Secret]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Update a Secret
     
     - parameter id: (path) The ID or name of the secret 
     - parameter version: (query) The version number of the secret object being updated. This is required to avoid conflicting writes. 
     - parameter body: (body) The spec of the secret to update. Currently, only the Labels field can be updated. All other fields must remain unchanged from the [SecretInspect endpoint](#operation/SecretInspect) response values. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func secretUpdate(id id: String, version: Int64, body: SecretSpec? = nil, completion: ((error: ErrorType?) -> Void)) {
        secretUpdateWithRequestBuilder(id: id, version: version, body: body).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Update a Secret
     - POST /secrets/{id}/update
     
     - parameter id: (path) The ID or name of the secret 
     - parameter version: (query) The version number of the secret object being updated. This is required to avoid conflicting writes. 
     - parameter body: (body) The spec of the secret to update. Currently, only the Labels field can be updated. All other fields must remain unchanged from the [SecretInspect endpoint](#operation/SecretInspect) response values. (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func secretUpdateWithRequestBuilder(id id: String, version: Int64, body: SecretSpec? = nil) -> RequestBuilder<Void> {
        var path = "/secrets/{id}/update"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = body?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
